services:
  open-o:
    build:
      context: ./development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../.:/workspace            # Mapping the project root to /workspace inside the container
      - ~/.m2:/root/.m2            # Persistent Maven cache
    env_file:
      - ./development/config/shared/local.env
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      TZ: America/Toronto
    networks:
      - open-o-network
    depends_on:
      - db

  db:
    build:
      context: ./../
      dockerfile: ./.devcontainer/db/Dockerfile
    env_file:
      - ./development/config/shared/local.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-files:/var/lib/mysql
    environment:
      TZ: America/Toronto
      container: docker
    networks:
      - open-o-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2"

volumes:
  mariadb-files:
    driver: local

  m2-volume:
    driver: local

networks:
  open-o-network:
    driver: bridge
    name: open-o-network